export type Tier = "titanium" | "diamond" | "gold";

export interface Broker {
  id: string;
  name: string;
  tier: Tier;
  primary: string;
  secondary: string;
  code: string;
  tagline: string;
  features: [string, string, string];
}

export const BROKERS: Broker[] = [
  {
    id: "pp",
    name: "Pepperstone",
    tier: "titanium",
    primary: "#0E5ACA",
    secondary: "#1A2840",
    code: "PP",
    tagline: "Raw Spreads from 0.0 pips",
    features: ["MT4 / MT5 / cTrader", "Razor Account", "ASIC / FCA / CySEC regulated"],
  },
  {
    id: "ex",
    name: "Exness",
    tier: "titanium",
    primary: "#FFDE02",
    secondary: "#0A0C10",
    code: "EX",
    tagline: "#1 by Trading Volume Globally",
    features: ["Instant withdrawals 24/7", "MT4 / MT5", "FCA / CySEC / FSCA"],
  },
  {
    id: "xm",
    name: "XM Global",
    tier: "titanium",
    primary: "#C7000B",
    secondary: "#1B0000",
    code: "XM",
    tagline: "130+ Countries, No Re-quotes",
    features: ["Negative balance protection", "Free daily research", "MT4 / MT5"],
  },
  {
    id: "cap",
    name: "Capital.com",
    tier: "titanium",
    primary: "#E82127",
    secondary: "#180000",
    code: "CAP",
    tagline: "AI-Powered CFD Trading",
    features: ["AI bias detection", "3000+ instruments", "FCA / CySEC / ASIC"],
  },
  {
    id: "xtb",
    name: "XTB",
    tier: "diamond",
    primary: "#FF0000",
    secondary: "#100000",
    code: "XTB",
    tagline: "0% Commission on Real Stocks",
    features: ["xStation 5", "5500+ instruments", "Warsaw Stock Exchange listed"],
  },
  {
    id: "ava",
    name: "AvaTrade",
    tier: "diamond",
    primary: "#1B2B65",
    secondary: "#0A1030",
    code: "AVA",
    tagline: "9 Regulators Worldwide",
    features: ["AvaProtect & AvaOptions", "MT4 / MT5", "UAE regulated"],
  },
  {
    id: "ic",
    name: "IC Markets",
    tier: "diamond",
    primary: "#0057A5",
    secondary: "#001530",
    code: "IC",
    tagline: "True ECN — Execution Under 40ms",
    features: ["EUR/USD from 0.0 pips", "MT4 / MT5 / cTrader", "ASIC regulated"],
  },
  {
    id: "hfm",
    name: "HF Markets",
    tier: "diamond",
    primary: "#EE2624",
    secondary: "#150000",
    code: "HFM",
    tagline: "DFSA Dubai Licensed",
    features: ["Arabic support", "Copy trading", "DFSA / FCA"],
  },
  {
    id: "mb",
    name: "MultiBank",
    tier: "diamond",
    primary: "#1B2B5E",
    secondary: "#060C20",
    code: "MB",
    tagline: "20,000+ Instruments, 14 Licenses",
    features: ["Most regulated globally", "Est. 2005", "MENA offices"],
  },
  {
    id: "bb",
    name: "BlackBull",
    tier: "diamond",
    primary: "#E8E8E8",
    secondary: "#000000",
    code: "BB",
    tagline: "Institutional ECN Liquidity",
    features: ["MT4 / MT5 / cTrader / TradingView", "FMA New Zealand", "ECN access"],
  },
  {
    id: "fp",
    name: "FP Markets",
    tier: "diamond",
    primary: "#013B81",
    secondary: "#001030",
    code: "FP",
    tagline: "10,000+ Instruments, ECN from 0.0",
    features: ["Share CFDs", "ASIC / CySEC regulated", "Australian broker"],
  },
  {
    id: "ad",
    name: "ADSS",
    tier: "gold",
    primary: "#00E676",
    secondary: "#001A10",
    code: "AD",
    tagline: "Abu Dhabi Based, FSRA Licensed",
    features: ["Institutional prime brokerage", "ADGM regulated", "MT4 / MT5"],
  },
  {
    id: "van",
    name: "Vantage",
    tier: "gold",
    primary: "#E35205",
    secondary: "#1A0800",
    code: "VAN",
    tagline: "RAW ECN from 0.0 — 5M+ Users",
    features: ["Social trading", "ASIC / FCA", "Multiple award winner"],
  },
  {
    id: "al",
    name: "Alpari",
    tier: "gold",
    primary: "#F26522",
    secondary: "#1A0800",
    code: "AL",
    tagline: "Est. 1998 — 25 Years of Trading",
    features: ["PAMM accounts", "Copy trading", "MT4 / MT5"],
  },
  {
    id: "nc",
    name: "Noor Capital",
    tier: "gold",
    primary: "#00843D",
    secondary: "#001A0E",
    code: "NC",
    tagline: "UAE Based — Arabic First",
    features: ["UAE SCA + FCA licensed", "Islamic finance", "Noor Index"],
  },
  {
    id: "inx",
    name: "Infinox",
    tier: "gold",
    primary: "#0A2463",
    secondary: "#020A1E",
    code: "INX",
    tagline: "IX Social Copy Trading",
    features: ["FCA regulated", "100+ countries", "Alpine F1 partner"],
  },
  {
    id: "bds",
    name: "BDSwiss",
    tier: "gold",
    primary: "#E30613",
    secondary: "#0D0000",
    code: "BDS",
    tagline: "1.7M+ Users — EU Regulated",
    features: ["CySEC regulated", "Award-winning", "MENA presence"],
  },
  {
    id: "vt",
    name: "VT Markets",
    tier: "gold",
    primary: "#E8272C",
    secondary: "#0A0002",
    code: "VT",
    tagline: "1,000+ Instruments — ASIC",
    features: ["Newcastle United FC partner", "MT4 / MT5", "Australian regulated"],
  },
  {
    id: "tm",
    name: "TMGM",
    tier: "gold",
    primary: "#003EA6",
    secondary: "#001030",
    code: "TM",
    tagline: "Chelsea FC & Brooklyn Nets Partner",
    features: ["ASIC regulated", "MT4 / MT5", "Sports partnerships"],
  },
  {
    id: "fxv",
    name: "FXView",
    tier: "gold",
    primary: "#6D28D9",
    secondary: "#0D0520",
    code: "FXV",
    tagline: "Ultra-Low Cost ECN Trading",
    features: ["CySEC regulated", "Raw spreads 0.0", "MT5 · Finvasia Group"],
  },
  {
    id: "bm",
    name: "Base Markets",
    tier: "gold",
    primary: "#2196F3",
    secondary: "#001A30",
    code: "BM",
    tagline: "Gold, Oil, Commodities CFDs",
    features: ["Commodity CFDs specialist", "Gold / silver / oil / gas", "Fast execution"],
  },
  {
    id: "bp",
    name: "BlackBull Pro",
    tier: "gold",
    primary: "#F59E0B",
    secondary: "#1A1000",
    code: "BP",
    tagline: "Institutional Prime Brokerage",
    features: ["B2B solutions", "Tier-1 liquidity", "White label & IB programs"],
  },
];
